name: release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build-linux:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Install latest rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  default: true
                  override: true

            - name: Build
              run: cargo build --release --bin servum && strip target/release/servum && mv target/release/servum target/release/servum_amd64

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: target/release/servum_amd64
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    build-win:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Install latest rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  default: true
                  override: true

            - name: Build
              run: cargo build --release --bin servum

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: target/release/servum.exe
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    build-mac:
        runs-on: macos-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Install latest rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: x86_64-apple-darwin
                  default: true
                  override: true

            - name: Build for mac
              run: cargo build --release --bin servum && strip target/release/servum && mv target/release/servum target/release/servum_darwin

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: target/release/servum_darwin
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
